import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { WebVitals } from "./_components/web-vitals";
import SessionWrapper from "./_components/SessionWrapper";
import { signOut } from "next-auth/react";
import Header from "./_components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={inter.className}>
          {/* <WebVitals /> */}
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
